import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Aymen',
      email: 'admin1@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Samsung',
        logo: '/images/logo.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Dalila',
      email: 'admin2@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Apple',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Ali',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Wyze Cam v3 w',
      category: 'Cameras',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'WYZE',
      rating: 4.5,
      numReviews: 10.807,
      description: 'Wyze Cam v3 w / Color Night Vision, Indoor / Outdoor 1080p HD Wired Video Camera, Two-Way Audio, Works with Alexa, Google Assistant and IFTTT',
    },
    {
      name: 'Samsung 27-Inch LC27RG50FQNXZA ',
      category: 'Screens',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Samsung',
      rating: 4.0,
      numReviews: 1.09,
      description: 'Samsung 27-Inch LC27RG50FQNXZA Curved Gaming Monitor (LC27RG50FQNXZA) - Computer Monitor, 1920 x 1080 Resolution, 4ms Response Time, G-Sync Compatible, HDMI, Black',
    },
    {
      name: 'Mini projector',
      category: 'Computers and accessories',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'VANNECT',
      rating: 4.8,
      numReviews: 32,
      description: 'Mini projector, [202020 upgrade] 4500 lumens, 1080p 220 "screen, compatible with phone, computer, laptop, USB, HDMI, VGA',
    },
    {
      name: 'Ring Wired Video Doorbell - Convenient',
      category: 'Doorbell',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Ring',
      rating: 4.5,
      numReviews:  374,
      description: 'Introducing the Ring Wired Video Doorbell - Convenient and essential features in a slim design (existing doorbell wiring required) - version 2021',
    },
    {
      name: 'Black Onyx',
      category: 'watch',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'UMIDIGI',
      rating: 4.5,
      numReviews:  1.442,
      description: 'UMIDIGI Smart Watch, Built-in GPS, Heart Rate Monitor, Activity Monitor with 1.3 inch Touch Screen, 5 ATM Waterproof Smart Watch for Men and Women, Compatible with iPhone and Android Phone.',
    },
    {
      name: 'Blue Microphones',
      category: 'Microphones',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'yeti',
      rating: 4.5,
      numReviews:  33.166,
      description: 'The microphone is compatible with Windows 8, 7, Vista, XP (Home and Professional), and Mac OS X (10.4.11 or higher), and requires a minimum free space of 64 MB of RAM.',
    },
  ],
};
export default data;